version: "3"

services:
  lumus8x:
    build: .
    restart: always
    ports: 
      - '8000:80'
    volumes:
      - ./lumus8x:/var/lumus8x/html
    networks: 
      - default
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_DATABASE: meudb
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
    networks: 
      - default
volumes:
  db_data: